(TOP (X_SBARQ (WHNP (WHNP_WDT Which) (PP (IN of) (NP_DT these))) (SQ_VP (VBP serve) (NP_NN dinner))) (PUNC ?))
(TOP (NP (NP (WDT Which) (NNS ones)) (VP (VBP stop) (PP (IN in) (NP_NNP Nashville)))) (PUNC ?))
(TOP (SQ (INTJ_UH <unk>) (SQ* (NP_NP_EX there) (SQ* (NP (DT any) (NNS flights)) (VP (VBG arriving) (PP (IN after) (NP (CD eleven) (RB a.m))))))) (PUNC ?))
(TOP (SBAR (WHNP (WDT What) (NNS flights)) (SQ (VBP do) (SQ* (NP_PRP you) (VP (VBP have) (PP (IN from) (NP_NNP Ontario)))))) (PUNC ?))
(TOP (SBAR (WHNP (WHNP (WDT What) (NN type)) (PP (IN of) (NP_NN aircraft))) (SQ (VBZ is) (NP (NP (NNP <unk>) (POS "s")) (NP (NP_NN flight) (NP* (CD two) (NP* (SYM <unk>) (CD two))))))) (PUNC ?))
(TOP (SQ (VBZ Does) (NP (NP (DT the) (JJ other)) (NP (NNP American) (NN flight)))) (PUNC ?))
(TOP (S (NP_PRP I) (VP (MD "d") (VP (VB like) (S_VP (TO to) (VP (VBP fly) (VP* (PP (IN from) (NP_NNP Tampa)) (PP (TO to) (NP_NNP Montreal)))))))) (PUNC .))
(TOP (S (PP (IN On) (NP_NNP Tuesday)) (S* (NP_PRP I) (VP (MD "d") (VP (VB like) (S_VP (TO to) (VP (VBP fly) (VP* (PP (IN from) (NP_NNP Detroit)) (PP (TO to) (NP (NNP Saint) (NNP Petersburg)))))))))) (PUNC .))
(TOP (FRAG_WHNP (NP (NP_NN Flight) (PP (IN from) (NP (NNP Long) (NNP Beach)))) (WHNP* (PP (TO to) (NP_NNP Columbus)) (PP (IN on) (NP (CD twenty) (NN <unk>))))) (PUNC .))
(TOP (NP (NP (WDT Which) (NNS ones)) (VP (VBP leave) (PP (IN in) (NP (DT the) (NN morning))))) (PUNC ?))
(TOP (X_SBARQ (WHNP (WHNP_WDT Which) (PP (IN of) (NP (DT these) (NNS flights)))) (SQ_VP (VBP serve) (NP_NN dinner))) (PUNC ?))
(TOP (SBAR (WHNP_WDT Which) (S_VP (VBZ is) (ADVP_RB last))) (PUNC ?))
(TOP (X_S_VP (VB Show) (VP* (NP_PRP me) (PP (NP (PDT all) (NP* (DT the) (NNS fares))) (PP* (IN from) (NP (NP (NP (NP (CD one) (NN way)) (NNS fares)) (PP (IN from) (NP_NNP Tacoma))) (PP (TO to) (NP_NNP Montreal))))))) (PUNC .))
(TOP (NP (NP (WDT Which) (NNS flights)) (VP (VB serve) (NP_NNS <unk>))) (PUNC ?))
(TOP (X_S_VP (VB List) (VP* (NP (NP (DT all) (NNS flights)) (PP (IN from) (NP_NNP Burbank))) (PP (TO to) (NP_NNP Denver)))) (PUNC .))
(TOP (SQ (INTJ_UH <unk>) (SQ* (NP_NP_EX there) (SQ* (NP (NP (NP (DT any) (NNS stopovers)) (PP (IN for) (NP_NNP Delta))) (NP (CD one) (CD seven))) (NP (CD three) (CD nine))))) (PUNC ?))
(TOP (SBAR (WHNP (WDT What) (NNS flights)) (SQ (VBP are) (SQ* (NP_NP_EX there) (SQ* (PP (IN from) (NP_NNP Houston)) (PP (TO to) (NP_NNP Dallas)))))) (PUNC ?))
(TOP (SBAR (WHNP (WDT What) (NNS flights)) (SQ (VBP are) (SQ* (NP_NP_EX there) (SQ* (PP (IN from) (NP_NNP Memphis)) (PP (TO to) (NP (NNP Las) (NNP Vegas))))))) (PUNC ?))
(TOP (NP (NP (NP_NNS Flights) (PP (IN from) (NP_NNP Cleveland))) (PP (TO to) (NP_NNP Miami))) (PUNC .))
(TOP (FRAG_WHNP (NP (NP_NNS Flights) (PP (IN on) (NP_NNP Sunday))) (WHNP* (PP (IN from) (NP_NNP Tampa)) (PP (TO to) (NP_NNP Charlotte)))) (PUNC .))
(TOP (FRAG_WHNP (NP (NP_NNS Flights) (VP (VBG arriving) (PP (IN in) (NP (NNP Las) (NNP Vegas))))) (WHNP* (PP (IN from) (NP (NP (NP_NNP Memphis) (NP* (CC and) (NNP New))) (NP (NNP York) (NNP City)))) (PP (IN on) (NP_NNP Sunday)))) (PUNC .))
(TOP (X_S_VP (VB Show) (VP* (NP_PRP me) (NP (DT the) (NN fare)))) (PUNC .))
(TOP (FRAG_PP (IN From) (NP (NP_NNP Toronto) (NP* (PP (TO to) (NP_NNP Atlanta)) (PP (IN in) (NP (DT the) (NN afternoon)))))) (PUNC .))
(TOP (FRAG_WHNP (WHNP (WHNP (WDT What) (NNS flights)) (PP (IN from) (NP (NNP Kansas) (NNP City)))) (PP (TO to) (NP_NNP Denver))) (PUNC .))
(TOP (FRAG_WHNP (WHNP (WHNP (WDT What) (NNS flights)) (PP (IN from) (NP (NP_NNP Washington) (NP* (NNP D) (NNP C))))) (PP (TO to) (NP_NNP Toronto))) (PUNC .))
(TOP (X_S_VP (VB <unk>) (VP* (NP (NP_DT any) (PP (IN of) (NP_DT those))) (PP (IN on) (NP (NNP American) (NNP Airlines))))) (PUNC ?))
(TOP (FRAG_WHNP (WHNP (WHNP (WHNP (WDT What) (NNS flights)) (PP (IN from) (NP_NNP Montreal))) (PP (TO to) (NP (NNP Las) (NNP Vegas)))) (PP (IN on) (NP_NNP Saturday))) (PUNC .))
(TOP (SBARQ (WHNP_WP What) (SQ (VBZ is) (NP (DT the) (NN price)))) (PUNC ?))
(TOP (FRAG_PP (IN On) (NP_NNP Thursday)) (PUNC .))
(TOP (NP (NP (NP_NNS Flights) (PP (IN from) (NP_NNP Cleveland))) (PP (TO to) (NP (NNP Kansas) (NNP City)))) (PUNC .))
(TOP (NP (NP (NP (NP_NN Price) (PP (IN from) (NP_NNP Cleveland))) (PP (TO to) (NP (NNP Kansas) (NNP City)))) (NP (JJ round) (NN trip))) (PUNC .))
(TOP (NP (NP (NP_NNS Flights) (PP (IN from) (NP_NNP Ontario))) (SBAR_S_VP (TO to) (VP_VB <unk>))) (PUNC .))
(TOP (FRAG_WHNP (NP (NP (JJ First) (NN class)) (NP (JJ round) (NP* (NN trip) (NN airfare)))) (WHNP* (PP (IN from) (NP_NNP Indianapolis)) (PP (TO to) (NP_NNP Memphis)))) (PUNC .))
(TOP (NP (NP (NP_NNS Flights) (PP (IN from) (NP_NNP Boston))) (PP (TO to) (NP_NNP Pittsburgh))) (PUNC .))
(TOP (NP (NP (NP_NNS Flights) (PP (IN from) (NP (NNP New) (NNP York)))) (PP (TO to) (NP_NNP Miami))) (PUNC .))
(TOP (FRAG_VP (VBG Departing) (PP (IN before) (NP (CD ten) (RB a.m)))) (PUNC .))
(TOP (NP (JJS Cheapest) (NN fare)) (PUNC .))
(TOP (FRAG_VP (VBG Departing) (PP (IN after) (NP (CD six) (RB p.m)))) (PUNC .))
(TOP (FRAG_VP (VBG Departing) (VP* (NP_NNP Wednesday) (PP (IN after) (NP (CD five) (RB "oclock"))))) (PUNC .))
(TOP (X_S_VP (VB Show) (VP* (NP_PRP me) (PP (NP (NN ground) (NN transportation)) (PP* (IN in) (NP (NNP Westchester) (NNP County)))))) (PUNC .))
(TOP (FRAG (NP_NNP Newark) (PP (TO to) (NP_NNP Cleveland))) (PUNC .))
(TOP (NP (NP_NN Airline) (NP* (NNP T) (NP* (NNP W) (NNP A)))) (PUNC .))
(TOP (X_S_VP (VB Show) (VP* (NP_PRP me) (NP (DT the) (NNS fares)))) (PUNC .))
(TOP (X_S_VP (VB Show) (VP* (NP_PRP me) (NP (NP (NP (DT the) (NNS fares)) (PP (IN from) (NP_NNP Dallas))) (PP (TO to) (NP (NNP San) (NNP Francisco)))))) (PUNC .))
(TOP (X_S_VP (VB Show) (VP* (NP_PRP me) (PP (NP (NP (NP (DT the) (NNS flights)) (PP (IN from) (NP (NNP San) (NNP Diego)))) (PP (TO to) (NP (NNP San) (NNP Francisco)))) (PP* (IN on) (NP (NNP Southwest) (NNP Airlines)))))) (PUNC .))
(TOP (X_S_VP (VB Show) (VP* (NP_PRP me) (NP (DT the) (JJ <unk>)))) (PUNC .))
